name: Unittest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        cd $GITHUB_WORKSPACE
        cd ./p01/deploy/
        ./setup-github-python.sh

    - name: Unittest
      run: |
        cd $GITHUB_WORKSPACE
        cd ./p01/tests/
        ./run_unittest.sh
