name: Unittest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        cd $GITHUB_WORKSPACE
        cd ./p01/deploy/
        ./generate-versionid.sh
        ./setup-github-python.sh


    - name: Unittest
      run: |
        cd $GITHUB_WORKSPACE
        cd ./p01/tests/
        ./run_unittest.sh
        ./run_pytest.sh
        ./run_pylint.sh

    - name: Build pkg
      run: |
        cd $GITHUB_WORKSPACE
        cd ./p01/deploy/
        ./make_whl.sh

    - name: Build Docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        cd $GITHUB_WORKSPACE
        cd ./p01/deploy/
        ./docker-build.sh

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          p01/dist

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: p01/tests/htmlcov